// Code generated by go-swagger; DO NOT EDIT.

package query_rates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetRatesIDOKCode is the HTTP code returned for type GetRatesIDOK
const GetRatesIDOKCode int = 200

/*GetRatesIDOK OK

swagger:response getRatesIdOK
*/
type GetRatesIDOK struct {
}

// NewGetRatesIDOK creates GetRatesIDOK with default headers values
func NewGetRatesIDOK() *GetRatesIDOK {

	return &GetRatesIDOK{}
}

// WriteResponse to the client
func (o *GetRatesIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
