// Code generated by go-swagger; DO NOT EDIT.

package query_rates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetAvgratesOKCode is the HTTP code returned for type GetAvgratesOK
const GetAvgratesOKCode int = 200

/*GetAvgratesOK OK

swagger:response getAvgratesOK
*/
type GetAvgratesOK struct {
}

// NewGetAvgratesOK creates GetAvgratesOK with default headers values
func NewGetAvgratesOK() *GetAvgratesOK {

	return &GetAvgratesOK{}
}

// WriteResponse to the client
func (o *GetAvgratesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
