// Code generated by go-swagger; DO NOT EDIT.

package query_rates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAvgratesHandlerFunc turns a function with the right signature into a get avgrates handler
type GetAvgratesHandlerFunc func(GetAvgratesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAvgratesHandlerFunc) Handle(params GetAvgratesParams) middleware.Responder {
	return fn(params)
}

// GetAvgratesHandler interface for that can handle valid get avgrates params
type GetAvgratesHandler interface {
	Handle(GetAvgratesParams) middleware.Responder
}

// NewGetAvgrates creates a new http.Handler for the get avgrates operation
func NewGetAvgrates(ctx *middleware.Context, handler GetAvgratesHandler) *GetAvgrates {
	return &GetAvgrates{Context: ctx, Handler: handler}
}

/*GetAvgrates swagger:route GET /avgrates Query Rates getAvgrates

Get Rates, Averaged. This will return averaged rates from all reports.

Get average rates filtered by location

*/
type GetAvgrates struct {
	Context *middleware.Context
	Handler GetAvgratesHandler
}

func (o *GetAvgrates) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAvgratesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
