// Code generated by go-swagger; DO NOT EDIT.

package query_rates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Tech4GoodPH/go-sample-api.git/models"
)

// GetRatesOKCode is the HTTP code returned for type GetRatesOK
const GetRatesOKCode int = 200

/*GetRatesOK OK

swagger:response getRatesOK
*/
type GetRatesOK struct {

	/*
	  In: Body
	*/
	Payload models.Posts `json:"body,omitempty"`
}

// NewGetRatesOK creates GetRatesOK with default headers values
func NewGetRatesOK() *GetRatesOK {

	return &GetRatesOK{}
}

// WithPayload adds the payload to the get rates o k response
func (o *GetRatesOK) WithPayload(payload models.Posts) *GetRatesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get rates o k response
func (o *GetRatesOK) SetPayload(payload models.Posts) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRatesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Posts{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
