// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/Tech4GoodPH/go-sample-api.git/restapi/operations/query_posts"
	"github.com/Tech4GoodPH/go-sample-api.git/restapi/operations/query_rates"
	"github.com/Tech4GoodPH/go-sample-api.git/restapi/operations/report"
)

// NewGoSampleAPI creates a new GoSample instance
func NewGoSampleAPI(spec *loads.Document) *GoSampleAPI {
	return &GoSampleAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		ReportDeleteReportHandler: report.DeleteReportHandlerFunc(func(params report.DeleteReportParams) middleware.Responder {
			return middleware.NotImplemented("operation ReportDeleteReport has not yet been implemented")
		}),
		QueryRatesGetAvgratesHandler: query_rates.GetAvgratesHandlerFunc(func(params query_rates.GetAvgratesParams) middleware.Responder {
			return middleware.NotImplemented("operation QueryRatesGetAvgrates has not yet been implemented")
		}),
		QueryPostsGetPostsHandler: query_posts.GetPostsHandlerFunc(func(params query_posts.GetPostsParams) middleware.Responder {
			return middleware.NotImplemented("operation QueryPostsGetPosts has not yet been implemented")
		}),
		QueryPostsGetPostsMessiestHandler: query_posts.GetPostsMessiestHandlerFunc(func(params query_posts.GetPostsMessiestParams) middleware.Responder {
			return middleware.NotImplemented("operation QueryPostsGetPostsMessiest has not yet been implemented")
		}),
		QueryPostsGetPostsMostactiveHandler: query_posts.GetPostsMostactiveHandlerFunc(func(params query_posts.GetPostsMostactiveParams) middleware.Responder {
			return middleware.NotImplemented("operation QueryPostsGetPostsMostactive has not yet been implemented")
		}),
		QueryPostsGetPostsNewestHandler: query_posts.GetPostsNewestHandlerFunc(func(params query_posts.GetPostsNewestParams) middleware.Responder {
			return middleware.NotImplemented("operation QueryPostsGetPostsNewest has not yet been implemented")
		}),
		QueryPostsGetPostsTidiestHandler: query_posts.GetPostsTidiestHandlerFunc(func(params query_posts.GetPostsTidiestParams) middleware.Responder {
			return middleware.NotImplemented("operation QueryPostsGetPostsTidiest has not yet been implemented")
		}),
		QueryRatesGetRatesIDHandler: query_rates.GetRatesIDHandlerFunc(func(params query_rates.GetRatesIDParams) middleware.Responder {
			return middleware.NotImplemented("operation QueryRatesGetRatesID has not yet been implemented")
		}),
		ReportGetReportHandler: report.GetReportHandlerFunc(func(params report.GetReportParams) middleware.Responder {
			return middleware.NotImplemented("operation ReportGetReport has not yet been implemented")
		}),
		ReportPatchReportHandler: report.PatchReportHandlerFunc(func(params report.PatchReportParams) middleware.Responder {
			return middleware.NotImplemented("operation ReportPatchReport has not yet been implemented")
		}),
		ReportPostReportHandler: report.PostReportHandlerFunc(func(params report.PostReportParams) middleware.Responder {
			return middleware.NotImplemented("operation ReportPostReport has not yet been implemented")
		}),
	}
}

/*GoSampleAPI Basic API - HTTP and no Auth */
type GoSampleAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/io.go-sample-api.v1+json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/io.go-sample-api.v1+json" mime type
	JSONProducer runtime.Producer

	// ReportDeleteReportHandler sets the operation handler for the delete report operation
	ReportDeleteReportHandler report.DeleteReportHandler
	// QueryRatesGetAvgratesHandler sets the operation handler for the get avgrates operation
	QueryRatesGetAvgratesHandler query_rates.GetAvgratesHandler
	// QueryPostsGetPostsHandler sets the operation handler for the get posts operation
	QueryPostsGetPostsHandler query_posts.GetPostsHandler
	// QueryPostsGetPostsMessiestHandler sets the operation handler for the get posts messiest operation
	QueryPostsGetPostsMessiestHandler query_posts.GetPostsMessiestHandler
	// QueryPostsGetPostsMostactiveHandler sets the operation handler for the get posts mostactive operation
	QueryPostsGetPostsMostactiveHandler query_posts.GetPostsMostactiveHandler
	// QueryPostsGetPostsNewestHandler sets the operation handler for the get posts newest operation
	QueryPostsGetPostsNewestHandler query_posts.GetPostsNewestHandler
	// QueryPostsGetPostsTidiestHandler sets the operation handler for the get posts tidiest operation
	QueryPostsGetPostsTidiestHandler query_posts.GetPostsTidiestHandler
	// QueryRatesGetRatesIDHandler sets the operation handler for the get rates ID operation
	QueryRatesGetRatesIDHandler query_rates.GetRatesIDHandler
	// ReportGetReportHandler sets the operation handler for the get report operation
	ReportGetReportHandler report.GetReportHandler
	// ReportPatchReportHandler sets the operation handler for the patch report operation
	ReportPatchReportHandler report.PatchReportHandler
	// ReportPostReportHandler sets the operation handler for the post report operation
	ReportPostReportHandler report.PostReportHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *GoSampleAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *GoSampleAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *GoSampleAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *GoSampleAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *GoSampleAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *GoSampleAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *GoSampleAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the GoSampleAPI
func (o *GoSampleAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.ReportDeleteReportHandler == nil {
		unregistered = append(unregistered, "report.DeleteReportHandler")
	}

	if o.QueryRatesGetAvgratesHandler == nil {
		unregistered = append(unregistered, "query_rates.GetAvgratesHandler")
	}

	if o.QueryPostsGetPostsHandler == nil {
		unregistered = append(unregistered, "query_posts.GetPostsHandler")
	}

	if o.QueryPostsGetPostsMessiestHandler == nil {
		unregistered = append(unregistered, "query_posts.GetPostsMessiestHandler")
	}

	if o.QueryPostsGetPostsMostactiveHandler == nil {
		unregistered = append(unregistered, "query_posts.GetPostsMostactiveHandler")
	}

	if o.QueryPostsGetPostsNewestHandler == nil {
		unregistered = append(unregistered, "query_posts.GetPostsNewestHandler")
	}

	if o.QueryPostsGetPostsTidiestHandler == nil {
		unregistered = append(unregistered, "query_posts.GetPostsTidiestHandler")
	}

	if o.QueryRatesGetRatesIDHandler == nil {
		unregistered = append(unregistered, "query_rates.GetRatesIDHandler")
	}

	if o.ReportGetReportHandler == nil {
		unregistered = append(unregistered, "report.GetReportHandler")
	}

	if o.ReportPatchReportHandler == nil {
		unregistered = append(unregistered, "report.PatchReportHandler")
	}

	if o.ReportPostReportHandler == nil {
		unregistered = append(unregistered, "report.PostReportHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *GoSampleAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *GoSampleAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *GoSampleAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *GoSampleAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/io.go-sample-api.v1+json":
			result["application/io.go-sample-api.v1+json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *GoSampleAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/io.go-sample-api.v1+json":
			result["application/io.go-sample-api.v1+json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *GoSampleAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the go sample API
func (o *GoSampleAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *GoSampleAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/report"] = report.NewDeleteReport(o.context, o.ReportDeleteReportHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/avgrates"] = query_rates.NewGetAvgrates(o.context, o.QueryRatesGetAvgratesHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/posts"] = query_posts.NewGetPosts(o.context, o.QueryPostsGetPostsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/posts/messiest"] = query_posts.NewGetPostsMessiest(o.context, o.QueryPostsGetPostsMessiestHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/posts/mostactive"] = query_posts.NewGetPostsMostactive(o.context, o.QueryPostsGetPostsMostactiveHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/posts/newest"] = query_posts.NewGetPostsNewest(o.context, o.QueryPostsGetPostsNewestHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/posts/tidiest"] = query_posts.NewGetPostsTidiest(o.context, o.QueryPostsGetPostsTidiestHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/rates/{id}"] = query_rates.NewGetRatesID(o.context, o.QueryRatesGetRatesIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/report"] = report.NewGetReport(o.context, o.ReportGetReportHandler)

	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/report"] = report.NewPatchReport(o.context, o.ReportPatchReportHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/report"] = report.NewPostReport(o.context, o.ReportPostReportHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *GoSampleAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *GoSampleAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *GoSampleAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *GoSampleAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
