// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi go-sample-api
Basic API - HTTP and no Auth


    Schemes:
      http
      https
    Host: virtserver.swaggerhub.com
    BasePath: /api/v1
    Version: 1.0.0

    Consumes:
    - application/io.go-sample-api.v1+json

    Produces:
    - application/io.go-sample-api.v1+json

swagger:meta
*/
package restapi
