// Code generated by go-swagger; DO NOT EDIT.

package report

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetReportOKCode is the HTTP code returned for type GetReportOK
const GetReportOKCode int = 200

/*GetReportOK OK

swagger:response getReportOK
*/
type GetReportOK struct {
}

// NewGetReportOK creates GetReportOK with default headers values
func NewGetReportOK() *GetReportOK {

	return &GetReportOK{}
}

// WriteResponse to the client
func (o *GetReportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
