// Code generated by go-swagger; DO NOT EDIT.

package report

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Tech4GoodPH/go-sample-api.git/models"
)

// GetReportOKCode is the HTTP code returned for type GetReportOK
const GetReportOKCode int = 200

/*GetReportOK OK

swagger:response getReportOK
*/
type GetReportOK struct {

	/*
	  In: Body
	*/
	Payload models.Posts `json:"body,omitempty"`
}

// NewGetReportOK creates GetReportOK with default headers values
func NewGetReportOK() *GetReportOK {

	return &GetReportOK{}
}

// WithPayload adds the payload to the get report o k response
func (o *GetReportOK) WithPayload(payload models.Posts) *GetReportOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get report o k response
func (o *GetReportOK) SetPayload(payload models.Posts) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetReportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Posts{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
