// Code generated by go-swagger; DO NOT EDIT.

package report

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PatchReportHandlerFunc turns a function with the right signature into a patch report handler
type PatchReportHandlerFunc func(PatchReportParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchReportHandlerFunc) Handle(params PatchReportParams) middleware.Responder {
	return fn(params)
}

// PatchReportHandler interface for that can handle valid patch report params
type PatchReportHandler interface {
	Handle(PatchReportParams) middleware.Responder
}

// NewPatchReport creates a new http.Handler for the patch report operation
func NewPatchReport(ctx *middleware.Context, handler PatchReportHandler) *PatchReport {
	return &PatchReport{Context: ctx, Handler: handler}
}

/*PatchReport swagger:route PATCH /report Report patchReport

Update a report

Update a report

*/
type PatchReport struct {
	Context *middleware.Context
	Handler PatchReportHandler
}

func (o *PatchReport) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchReportParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
