// Code generated by go-swagger; DO NOT EDIT.

package report

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PatchReportOKCode is the HTTP code returned for type PatchReportOK
const PatchReportOKCode int = 200

/*PatchReportOK OK

swagger:response patchReportOK
*/
type PatchReportOK struct {
}

// NewPatchReportOK creates PatchReportOK with default headers values
func NewPatchReportOK() *PatchReportOK {

	return &PatchReportOK{}
}

// WriteResponse to the client
func (o *PatchReportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
