// Code generated by go-swagger; DO NOT EDIT.

package report

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostReportOKCode is the HTTP code returned for type PostReportOK
const PostReportOKCode int = 200

/*PostReportOK OK

swagger:response postReportOK
*/
type PostReportOK struct {
}

// NewPostReportOK creates PostReportOK with default headers values
func NewPostReportOK() *PostReportOK {

	return &PostReportOK{}
}

// WriteResponse to the client
func (o *PostReportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
