// Code generated by go-swagger; DO NOT EDIT.

package query_posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetPostsTidiestHandlerFunc turns a function with the right signature into a get posts tidiest handler
type GetPostsTidiestHandlerFunc func(GetPostsTidiestParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPostsTidiestHandlerFunc) Handle(params GetPostsTidiestParams) middleware.Responder {
	return fn(params)
}

// GetPostsTidiestHandler interface for that can handle valid get posts tidiest params
type GetPostsTidiestHandler interface {
	Handle(GetPostsTidiestParams) middleware.Responder
}

// NewGetPostsTidiest creates a new http.Handler for the get posts tidiest operation
func NewGetPostsTidiest(ctx *middleware.Context, handler GetPostsTidiestHandler) *GetPostsTidiest {
	return &GetPostsTidiest{Context: ctx, Handler: handler}
}

/*GetPostsTidiest swagger:route GET /posts/tidiest Query Posts getPostsTidiest

Get Tidiest Posts

Get tidiest posts filtered by location

*/
type GetPostsTidiest struct {
	Context *middleware.Context
	Handler GetPostsTidiestHandler
}

func (o *GetPostsTidiest) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPostsTidiestParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
