// Code generated by go-swagger; DO NOT EDIT.

package query_posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Tech4GoodPH/go-sample-api.git/models"
)

// GetPostsTidiestOKCode is the HTTP code returned for type GetPostsTidiestOK
const GetPostsTidiestOKCode int = 200

/*GetPostsTidiestOK OK

swagger:response getPostsTidiestOK
*/
type GetPostsTidiestOK struct {

	/*
	  In: Body
	*/
	Payload models.Posts `json:"body,omitempty"`
}

// NewGetPostsTidiestOK creates GetPostsTidiestOK with default headers values
func NewGetPostsTidiestOK() *GetPostsTidiestOK {

	return &GetPostsTidiestOK{}
}

// WithPayload adds the payload to the get posts tidiest o k response
func (o *GetPostsTidiestOK) WithPayload(payload models.Posts) *GetPostsTidiestOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get posts tidiest o k response
func (o *GetPostsTidiestOK) SetPayload(payload models.Posts) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPostsTidiestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Posts{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
