// Code generated by go-swagger; DO NOT EDIT.

package query_posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetPostsNewestHandlerFunc turns a function with the right signature into a get posts newest handler
type GetPostsNewestHandlerFunc func(GetPostsNewestParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPostsNewestHandlerFunc) Handle(params GetPostsNewestParams) middleware.Responder {
	return fn(params)
}

// GetPostsNewestHandler interface for that can handle valid get posts newest params
type GetPostsNewestHandler interface {
	Handle(GetPostsNewestParams) middleware.Responder
}

// NewGetPostsNewest creates a new http.Handler for the get posts newest operation
func NewGetPostsNewest(ctx *middleware.Context, handler GetPostsNewestHandler) *GetPostsNewest {
	return &GetPostsNewest{Context: ctx, Handler: handler}
}

/*GetPostsNewest swagger:route GET /posts/newest Query Posts getPostsNewest

Get Newest Posts

Get newest posts filtered by location

*/
type GetPostsNewest struct {
	Context *middleware.Context
	Handler GetPostsNewestHandler
}

func (o *GetPostsNewest) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPostsNewestParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
