// Code generated by go-swagger; DO NOT EDIT.

package query_posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetPostsMessiestOKCode is the HTTP code returned for type GetPostsMessiestOK
const GetPostsMessiestOKCode int = 200

/*GetPostsMessiestOK OK

swagger:response getPostsMessiestOK
*/
type GetPostsMessiestOK struct {
}

// NewGetPostsMessiestOK creates GetPostsMessiestOK with default headers values
func NewGetPostsMessiestOK() *GetPostsMessiestOK {

	return &GetPostsMessiestOK{}
}

// WriteResponse to the client
func (o *GetPostsMessiestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
