// Code generated by go-swagger; DO NOT EDIT.

package query_posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetPostsMostactiveOKCode is the HTTP code returned for type GetPostsMostactiveOK
const GetPostsMostactiveOKCode int = 200

/*GetPostsMostactiveOK OK

swagger:response getPostsMostactiveOK
*/
type GetPostsMostactiveOK struct {
}

// NewGetPostsMostactiveOK creates GetPostsMostactiveOK with default headers values
func NewGetPostsMostactiveOK() *GetPostsMostactiveOK {

	return &GetPostsMostactiveOK{}
}

// WriteResponse to the client
func (o *GetPostsMostactiveOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
