// Code generated by go-swagger; DO NOT EDIT.

package query_posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetPostsNewestOKCode is the HTTP code returned for type GetPostsNewestOK
const GetPostsNewestOKCode int = 200

/*GetPostsNewestOK OK

swagger:response getPostsNewestOK
*/
type GetPostsNewestOK struct {
}

// NewGetPostsNewestOK creates GetPostsNewestOK with default headers values
func NewGetPostsNewestOK() *GetPostsNewestOK {

	return &GetPostsNewestOK{}
}

// WriteResponse to the client
func (o *GetPostsNewestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
