// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// DiscussionThread discussion thread
// swagger:model DiscussionThread
type DiscussionThread struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this discussion thread
func (m *DiscussionThread) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DiscussionThread) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DiscussionThread) UnmarshalBinary(b []byte) error {
	var res DiscussionThread
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
